version: '3'

services:
  ollama:
    image: ollama/ollama
    hostname: ollama
    container_name: ollama
    volumes:
      - ollama:/root/.ollama
    ports:
      - "11434:11434"
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]

volumes:   # add this section
  ollama:    # does not need anything underneath this
